export const LOADING_FIVEDAYS_WEATHER = 'LOADING_FIVEDAYS_WEATHER'
export const SUCCESS_FIVEDAYS_WEATHER = 'SUCCESS_FIVEDAYS_WEATHER'
export const FAILURE_FIVEDAYS_WEATHER = 'FAILURE_FIVEDAYS_WEATHER'