export const LOADING_CURRENT_WEATHER = 'LOADING_CURRENT_WEATHER'
export const SUCCESS_CURRENT_WEATHER = 'SUCCESS_CURRENT_WEATHER'
export const FAILURE_CURRENT_WEATHER = 'FAILURE_CURRENT_WEATHER'

export const CLEAR_FAILURE_STATE = 'CLEAR_FAILURE_STATE'